-- Get the period set and period type for each OU
select  L.LEDGER_ID, L.CHART_OF_ACCOUNTS_ID, L.ACCOUNTED_PERIOD_TYPE, L.PERIOD_SET_NAME
,       O.ORGANIZATION_ID
from    HR_ORGANIZATION_INFORMATION O 
        INNER JOIN  GL_LEDGERS L
        ON     TO_NUMBER(O.ORG_INFORMATION3) = L.LEDGER_ID
        AND    TRANSLATE(O.ORG_INFORMATION3, '0123456789','') IS  NULL
        and    O.ORG_INFORMATION_CONTEXT = 'Operating Unit Information'
/




SELECT * FROM all_views WHERE view_name = 'HR_OPERATING_UNITS';

desc HR_OPERATING_UNITS
Name                     Null     Type          
------------------------ -------- ------------- 
BUSINESS_GROUP_ID        NOT NULL NUMBER(15)    
ORGANIZATION_ID          NOT NULL NUMBER(15)    
NAME                     NOT NULL VARCHAR2(240) 
DATE_FROM                NOT NULL DATE          
DATE_TO                           DATE          
SHORT_CODE                        VARCHAR2(150) 
SET_OF_BOOKS_ID                   VARCHAR2(150) 
DEFAULT_LEGAL_CONTEXT_ID          VARCHAR2(150) 
USABLE_FLAG                       VARCHAR2(150) 


SELECT O.BUSINESS_GROUP_ID ,
  O.ORGANIZATION_ID ,
  OTL.NAME ,
  O.DATE_FROM ,
  O.DATE_TO ,
  O3.ORG_INFORMATION5 ,
  O3.ORG_INFORMATION3 ,
  O3.ORG_INFORMATION2 ,
  O3.ORG_INFORMATION6
FROM HR_ALL_ORGANIZATION_UNITS O,
  HR_ALL_ORGANIZATION_UNITS_TL OTL,
  HR_ORGANIZATION_INFORMATION O2,
  HR_ORGANIZATION_INFORMATION O3
WHERE O.ORGANIZATION_ID = O2.ORGANIZATION_ID
AND O.ORGANIZATION_ID   = O3.ORGANIZATION_ID
AND O2.ORG_INFORMATION_CONTEXT
  ||''                         = 'CLASS'
AND O3.ORG_INFORMATION_CONTEXT = 'Operating Unit Information'
AND O2.ORG_INFORMATION1        = 'OPERATING_UNIT'
AND O2.ORG_INFORMATION2        = 'Y'
AND O.ORGANIZATION_ID          = OTL.ORGANIZATION_ID
AND OTL.LANGUAGE               = userenv('LANG')
/


select count(*) 
from HR_ALL_ORGANIZATION_UNITS OU 
where OU.ORGANIZATION_ID IN (
  SELECT OI1.ORGANIZATION_ID
  from   HR_ORGANIZATION_INFORMATION OI1
  where  OI1.ORG_INFORMATION_CONTEXT = 'Operating Unit Information')
and EXISTS (
  SELECT OI2.ORGANIZATION_ID
  from   HR_ORGANIZATION_INFORMATION OI2
  where  OI2.ORG_INFORMATION_CONTEXT = 'CLASS'
  AND OI2.ORG_INFORMATION2        = 'Y');



select * from all_tables where table_name like '%\_ALL' escape '\';
